apiVersion: v1
kind: Service
metadata:
  name: mywebapp-service
spec:
  type: LoadBalancer
  selector:
    app: mywebapp
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000  # O 5000 para Flask
